shap = (64,64,1)
inp = Input(shape=shap)
d1 = Conv2D(filters=20,kernel_size=3,strides=2,activation='relu',padding='same')(inp)
e1 = Conv2DTranspose(filters=1,kernel_size=3,strides=2,activation='relu',padding='same')(d1)
model = Model(inp,e1)
plot_model(model,to_file='model.png',show_shapes=True)
data = plt.imread('model.png')
plt.figure(figsize=(10,10))
plt.imshow(data,cmap='gray')
plt.savefig("cnn model plot")
plt.show()
model.summary()model.summary()
with open("model_summary.txt", "w", encoding="utf-8") as f:
    model.summary(print_fn=lambda x: f.write(x + "\n"))
    model.compile(optimizer='adam',loss="mse",metrics=['mse'])